version: '3.8'

services:
  app:
    image: supplychaintracking:2.7.0
    container_name: SupplyChainTracking
    environment:
      - NEXUS_URL=http://172.17.20.244:8081/repository/maven-releases/com/pgsintl/SupplyChainTracking/2.7/SupplyChainTracking-2.7.jar
    ports:
      - "8085:8085"
    command: ["java", "-jar", "/SupplyChainTracking-2.7.jar"]
    depends_on:
      - sqlserver
    volumes:
      - .:/app
    working_dir: /app

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPgsDb123
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MyPgsDb123 -Q "CREATE DATABASE pgsDB"
        /opt/mssql/bin/sqlservr

volumes:
  sqlserver-data:
